# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Greeting! I like Reb Lobster! lol
tagline:             "Eric Zhang"
description:         "Eric Zhang's Github"
url:                 https://Ericzhang90.github.io
paginate:            5

# About/contact
author:
  gravatar:          https://avatars1.githubusercontent.com/u/11701625?v=3&amp;s=400
  name:              Eric Zhang
  url:               https://github.com/EricZhang90
  email:             lzhang.eric@gmail.com

# Custom vars
version:             1.2.0

future: true

permalink: /:year-:month-:day-:title/
